### PR TITLE
feat(docs): Catalyst Gateway OpenAPI docs

### LINKED ISSUE #149: 🛠️ [TASK] : Add OpenAPI docs for catalyst Gateway to our docs.
### Summary

Embed the generated OpenAPI doc from Catalyst Gateway into our published docs.

### Description

We autogenerate an OpenAPI doc in Catalyst Gateway.
#143 is a pre-requisite

Take the generated and linted OpenAPI doc,  read the save artifact from the catalyst-gateway build, and inject it into the documentation build so it can be properly displayed.

### PR DESCRIPTION
**Pull request by Mr-Leshiy**
# Description

- Added generation of the catalyst gateway OpenAPI docs
- Integrated this docs to the MkDocs.

## Related Issue(s)

Closes #149 

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [ ] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

**Comment by Mr-Leshiy** [comment]
docs: https://input-output-hk.github.io/catalyst-voices/branch/feat_openai_docs

**Review by stevenj — CHANGES_REQUESTED** [review]
We should be rendering the docs like we do in cat-core.
See: 
* https://github.com/input-output-hk/catalyst-core/blob/main/book/templates/api_docs.template
* https://github.com/input-output-hk/catalyst-core/blob/main/book/src/07_web_api/catalyst-core-api.md
* https://input-output-hk.github.io/catalyst-core/main/07_web_api/catalyst-core-api.html

Even though that example has a title with version in the markdown file, its basically redundant, as its in the rendered docs themselves.  So we just need to embed the docs into a frame like that and skip the title in the markdown itself.

**Comment by Mr-Leshiy** [comment]
@stevenj , done, applied stoplight template

**Review by saibatizoku — DISMISSED** [review]
Looks right to me.

**Review by minikin — APPROVED** [review]

**Review by stevenj — APPROVED** [review]
LGTM

**Pull request merged**
