### PR TITLE
chore: upgrade flutter to 3.22.1

### PR DESCRIPTION
**Pull request by dtscalac**
# Description

- Upgrades Flutter to 3.22.1
- Upgrades dart to 3.3.4

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [x] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

**Review by coire1 — DISMISSED** [review]
LGTM

**Review by stevenj — CHANGES_REQUESTED** [review]
I believe some of this is superseded by the Flutter builders now released in Catalyst-CI.
Catalyst-CI should be the source of truth for pinned versions and controlled build files.
Please update this PR to use https://github.com/input-output-hk/catalyst-ci/releases/tag/v3.1.0

I am also assigning @bkioshn to this ticket as she can help with this process.

**Comment by stevenj** [comment]
I have converted this to a draft PR, just so its not accidentally merged pending the updates to use cat-ci flutter/dart tooling.

**Comment by dtscalac** [comment]
> I believe some of this is superseded by the Flutter builders now released in Catalyst-CI. Catalyst-CI should be the source of truth for pinned versions and controlled build files. Please update this PR to use https://github.com/input-output-hk/catalyst-ci/releases/tag/v3.1.0
> 
> I am also assigning @bkioshn to this ticket as she can help with this process.

The cat-ci tooling has been integrated into this PR, we can proceed with the review.

**Review by stevenj — APPROVED** [review]
LGTM

**Pull request merged**
