### PR TITLE
fix: Update `cat-gateway` rust build, cleaunup markdowns, code and earthly files

### PR DESCRIPTION
**Pull request by Mr-Leshiy**
# Description

- Updated `cat-gateway` rust build, remove using `cargo chef`.
- Bump rust toolchain version to `1.73.0`
- Cleanup earthly files and markdowns

## Related Pull Requests

https://github.com/input-output-hk/catalyst-ci/pull/54

### CODE REVIEW

**Comment by stevenj** [comment]
@Mr-Leshiy I think this is out of date now with respect to the Rust changes I ended up making.
Can you check it?

**Review by stevenj — CHANGES_REQUESTED** [review]
Please rebase this PR on the latest cat-gateway code,  some of these changes are already incorporated in the `main` and may not be 100% exactly as in the PR.

**Comment by Mr-Leshiy** [comment]
@stevenj yep, sure, checking it. 
With deeply in stepping PostgreSQL stuff, missed your comments

**Comment by Mr-Leshiy** [comment]
@stevenj closing this PR because it is not relevant anymore.
For minor fix I have created a new one https://github.com/input-output-hk/catalyst-voices/pull/114

**Comment by Mr-Leshiy** [comment]
@stevenj closing this PR because it is not relevant anymore.
For minor fix I have created a new one https://github.com/input-output-hk/catalyst-voices/pull/114

**Pull request closed without merging**
